import os
print(os.path.abspath('.'))
print(os.path.basename('/tmp/abc.py'))
print(os.path.commonpath(['/tmp/abc.py', '/tmp/def.py']))
print(os.path.commonprefix(['/usr/lib', '/usr/local/lib']))
print(os.path.dirname('/tmp/abc.py'))
print(os.path.exists('./0.py'))
print(os.path.lexists('./0.py'))
print(os.path.expanduser('./0.py'))
print(os.path.expandvars('./0.py'))
print(os.path.getatime('./0.py'))
print(os.path.getmtime('./0.py'))
print(os.path.getctime('./0.py'))
print(os.path.getsize('./0.py'))
print(os.path.isabs('./0.py'))
print(os.path.isfile('./0.py'))
print(os.path.isdir('./0.py'))
print(os.path.islink('./0.py'))
print(os.path.ismount('./0.py'))
print(os.path.join('./0.py'))
print(os.path.normcase('./0.py'))
print(os.path.normpath('./0.py'))
print(os.path.realpath('./0.py'))
print(os.path.relpath('./0.py'))
print(os.path.samefile('./0.py', './0.py'))
#    print(os.path.sameopenfile(os.open('./0.py'), os.open('./0.py')))
#with open('./0.py') as f:
#    print(os.path.sameopenfile(f, f))
#print(os.path.sameopenfile(open('./0.py'), open('./0.py')))
#print(os.path.sameopenfile('./0.py', './0.py'))
#print(os.path.samestat('./0.py'))
print(os.path.split('./0.py'))
print(os.path.splitdrive('./0.py'))
print(os.path.splitext('./0.py'))
#print(os.path.splitunc('./0.py'))#バージョン 3.1 で撤廃: 代わりに splitdrive を使ってください。
print(os.path.supports_unicode_filenames)
